---

- name: start ssh service
  service:
    name: "{{ ssh_service }}"
    state: started
    enabled: true
  listen:
  notify: "restart ssh service"
  tags:
    - start-ssh

- name: restart ssh service
  service:
    name: "{{ ssh_service }}"
    state: restarted
    enabled: true
  listen: "restart ssh service"
  tags:
    - restart-ssh
