---

- name: start ssh service
  service:
    name: "{{ ssh_service }}"
    state: started
    enabled: true
  tags:
    - start-ssh

- name: restart ssh service
  service:
    name: "{{ ssh_service }}"
    state: restarted
    enabled: true
  tags:
    - restart-ssh
